### ISSUE TITLE
Help fatx windows 10

### ISSUE THREAD

**Issue by aRUNTU** [mborgerson/fatx#66]
Hello! I know this is not a pyfatx related question, but following the instructions I have this error:

**PS C:\WINDOWS\system32> pip install --use-pep517
ERROR: You must give at least one requirement to install (see "pip help install")
PS C:\WINDOWS\system32> pip install --use-pep517 pyfatx
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pyfatx/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pyfatx/
Collecting pyfatx
  Using cached pyfatx-0.0.7.tar.gz (36 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cffi (from pyfatx)
  Using cached cffi-1.16.0-cp312-cp312-win_amd64.whl.metadata (1.5 kB)
Collecting pycparser (from cffi->pyfatx)
  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Using cached cffi-1.16.0-cp312-cp312-win_amd64.whl (181 kB)
Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Building wheels for collected packages: pyfatx
  Building wheel for pyfatx (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyfatx (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [93 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\pyfatx
      copying pyfatx\__init__.py -> build\lib.win-amd64-cpython-312\pyfatx
      copying pyfatx\__main__.py -> build\lib.win-amd64-cpython-312\pyfatx
      running build_ext
      generating cffi module 'build\\temp.win-amd64-cpython-312\\Release\\pyfatx.libfatx.c'
      creating build\temp.win-amd64-cpython-312
      creating build\temp.win-amd64-cpython-312\Release
      -- Building for: Visual Studio 16 2019
      CMake Deprecation Warning at CMakeLists.txt:18 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      -- The C compiler identification is unknown
      -- The CXX compiler identification is unknown
      CMake Error at CMakeLists.txt:20 (project):
        No CMAKE_C_COMPILER could be found.

      CMake Error at CMakeLists.txt:20 (project):
        No CMAKE_CXX_COMPILER could be found.

      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Users\isaac\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\isaac\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\isaac\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\overlay\Lib\site-packages\setuptools\build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\overlay\Lib\site-packages\setuptools\build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 9, in <module>
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\overlay\Lib\site-packages\setuptools\dist.py", line 968, in run_command
          super().run_command(command)
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\normal\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\overlay\Lib\site-packages\setuptools\dist.py", line 968, in run_command
          super().run_command(command)
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\overlay\Lib\site-packages\setuptools\dist.py", line 968, in run_command
          super().run_command(command)
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\normal\Lib\site-packages\cffi\setuptools_ext.py", line 141, in run
          ext.sources[0] = make_mod(self.build_temp, pre_run)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\isaac\AppData\Local\Temp\pip-build-env-ot4uiq_a\normal\Lib\site-packages\cffi\setuptools_ext.py", line 126, in make_mod
          pre_run(ext, ffi)
        File "C:\Users\isaac\AppData\Local\Temp\pip-install-l2faki4w\pyfatx_ec27292bf3ab4dcbae31f95f1f3b212d\build_cffi.py", line 34, in pre_run
          subprocess.check_call(['cmake', '-B', 'build'] + cmake_config_args, cwd=ROOT_DIR)
        File "C:\Users\isaac\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '-B', 'build', '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON', '-A', 'x64']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyfatx
Failed to build pyfatx
ERROR: Could not build wheels for pyfatx, which is required to install pyproject.toml-based projects
PS C:\WINDOWS\system32>**

also

**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.36
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>

also

PS C:\WINDOWS\system32> pip install cmake
Requirement already satisfied: cmake in c:\users\isaac\appdata\local\programs\python\python312\lib\site-packages (3.29.3)
PS C:\WINDOWS\system32>

also added path

C:\Users\isaac\AppData\Local\Programs\Python\Python312\Lib\site-packages\cmake\data\bin\cmake.exe

to windows 10 

Any help please???

**Comment by aRUNTU** [comment]
solved by installing ms dev kit
